version: '3.7'

services:
  web:
    build: .
    command: flask run 
    volumes:
      - .:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - netldm
 
  db:
    image: postgres:12.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ldmusic
      - POSTGRES_DB=ldm_dev
    networks:
      - netldm
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ldmusic00@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "ldmusic"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - netldm

volumes:
  postgres_data:

networks:
  netldm:
    driver: bridge
