version: '3'

services:
  
  db:
    image: mysql:latest
    container_name: ldmusic_mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ldmusic
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=ldmusic
    volumes: 
      - ./db-volumes:/var/lib/mysql
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
